### ISSUE TITLE
Use glk

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/ifvms.js#18]
Port ZVM to use Glk as its output system. Match Quixe for the general API.

Possibly develop a JS terminal Glk implementation for use as a terminal interpreter.

**Comment by curiousdannii** [comment]
@erkyrath I'm starting to port ZVM to use Glk, and have a couple of questions.

How would you feel about renaming the init() function of Quixe to start()? My class system uses init for constructors. At the moment I'm overwriting the init function so it's not a big issue.

Should ZVM stop buffering text and let Glk handle that?

**Comment by erkyrath** [comment]
Sorry, I let this slip... 

I don't want to rearrange the function names in the Quixe interface just for this. You could rename them at load time, e.g. say `Quixe.originit = Quixe.init` and go on from there.

Yes, Glk is enthusiastic about buffering output so the VM doesn't have to.

**Comment by curiousdannii** [comment]
Yeah renaming at run time is easy.

The conversion has been surprisingly easy! The next thing to do is the status window functions, which I had previously just handed off to Parchment to do. I noticed from Bocfel that even something like keeping track of the cursor has to be done manually.

**Comment by curiousdannii** [comment]
In the future I'd like to get better style support, but for now I think Glk support is pretty much complete.

**Comment by erkyrath** [comment]
Ok, cool.
