### ISSUE TITLE
Include polyfills for TypedArray methods

### ISSUE THREAD

**Issue by juhana** [curiousdannii/ifvms.js#22]
At least `Uint8Array.slice()` and `Uint8Array.indexOf()` don't work in Safari and IE.

**Comment by curiousdannii** [comment]
For the record, they are supported in Edge (12), Firefox 38, Chrome 45, Opera 32, Node 4.

It seems like no version of Safari, or the default Android or iOS browsers support them, so polyfills will be needed, we can't just ask or wait for people to upgrade from IE to Edge.

**Comment by curiousdannii** [comment]
Found it: Uint8Array.indexOf() is being used on dictionary.separators.
