### ISSUE TITLE
MemoryView does not accept plain arrays

### ISSUE THREAD

**Issue by erkyrath** [curiousdannii/ifvms.js#26]
There's a line at the top:

    if ( typeof buffer === 'number' )

I take it this is intended to convert a plain array to an ArrayBuffer, but it doesn't work as written. I changed it to 

    if ( typeof buffer[0] === 'number' )

...in my work tree, which I think is what you meant.

**Comment by erkyrath** [comment]
Never mind, I misread what this is trying to do. Sorry.

**Comment by curiousdannii** [comment]
It wouldn't be too hard to make it accept an array, but it's just as easy to convert the array to a Uint8Array first.

**Comment by erkyrath** [comment]
Yeah, that worked.
