### ISSUE TITLE
"inventory" hangs in Advent.z5

### ISSUE THREAD

**Issue by erkyrath** [curiousdannii/ifvms.js#29]
In the attached version of Advent.z5, enter

> e
> get all
> i

The engine locks up (spinning) on the inventory command.

It's definitely the "i" going wrong, not the "get all". The attached save file was made in Frotz with "e", "get all", "save". So the game state is correct there. But when loaded into ZVM, "i" still locks up.

(This is the standard Advent.inf, but I've recompiled it so it's not exactly the same binary as on the Archive. That one shows the same bug, though.) (The files are zipped together because Github won't take raw files of unrecognized type.)

[testfiles.zip](https://github.com/curiousdannii/ifvms.js/files/679501/testfiles.zip)

**Comment by curiousdannii** [comment]
I've seen some other games hang too. Will investigate.

**Comment by erkyrath** [comment]
Poking around, I see that it's getting stuck at PC=58783, repeatedly running the JIT function

    anonymous(e
    /**/) {
     var l=e.l,s=e.s;
    /* 58783/225 */ e.ram.setUint16(e.S2U(16348+2*0),160);/* 58789/243 */ e.output_stream(3,16348)
    }

**Comment by erkyrath** [comment]
I tried the "obvious" fix:

    /* output_stream */ 243: opcode_builder( Stopper, function() { return 'e.pc=' + this.next + ';e.output_stream(' + this.args() + ')'; } ),

That seems to solve it.

**Comment by erkyrath** [comment]
Now, I see a second problem -- this is almost certainly unrelated, so I can open a second issue if you want, but it's with the same Advent.z5:

If you type HELP and then immediately quit out of the help menu, you get into a state where the status window is closed and the text that should go to the status window goes to the story window instead.
