### ISSUE TITLE
Status line disappears in Advent.z5

### ISSUE THREAD

**Issue by erkyrath** [curiousdannii/ifvms.js#31]
Split from comment in https://github.com/curiousdannii/ifvms.js/issues/29 : 

If you type HELP and then immediately quit out of the help menu, you get into a state where the status window is closed and the text that should go to the status window goes to the story window instead.

**Comment by erkyrath** [comment]
After digging into various interpreters, here's what I find:

We have a de-facto rule that if you call set_cursor with a nonexistent row number, the status window height increases to allow that row to exist. Fizmo, GarGlk+Frotz, and the old Parchment both do this. The I6 library apparently relies on this behavior.

My patch adds the appropriate test to set_cursor, but it also required a couple of other changes. In set_window, I moved the glk_set_window() and format() calls to *after* the set_cursor call -- before that call, upperwin may not exist yet. I also added a `this.io.height = 0` in one spot in split_window where it was missing.

With this change, Advent.z5 and Curses.z5 both handle their status lines correctly.

(Except that the Curses.z5 quote boxes still don't work. That will require special-case logic -- you've seen my notes on the subject.)

**Comment by curiousdannii** [comment]
When I wrote the windowing code from scratch using Glk I decided to stick to only what the standard said, and to only add support for non-standard behaviour once there were clear examples of it, because I couldn't remember which story files exactly needed what, and whether all that was supported actually needed to be.

Thanks for the diagnosis and the patch!

**Comment by curiousdannii** [comment]
I've also given you commit access to the repository if you'd prefer to commit directly instead of making PRs.

**Comment by erkyrath** [comment]
Thanks. I'll still do PRs, in general, so you can look stuff over.
