### ISSUE TITLE
V3/5/8 zvm.min.js

### ISSUE THREAD

**Issue by twistylittleworkshop** [curiousdannii/ifvms.js#34]
Hi,

Thought I'd posted this, but cannot find it now! Apologies if duped.

Will there be a one-file zvm.min.js release for the new V3 update?

Thanks.

**Comment by twistylittleworkshop** [comment]
Ah! Found it in the parchment issues list - apologies again for the dupe.

For anyone stumbling on this, the answer was "not yet".

**Comment by curiousdannii** [comment]
It's easy enough to minify manually, but if you'd like the files added to the releases page I can do that too.

**Comment by erkyrath** [comment]
Putting the files on the release page would be slightly more convenient for me.

**Comment by twistylittleworkshop** [comment]
If it is trivial and won't cause you too much grief, a link on the releases page would be great. I can get testing my Lost Treasures collections then!

**Comment by curiousdannii** [comment]
Alright, I've uploaded the 0.2.2 files to the releases page, and will do so again for future releases.

**Comment by erkyrath** [comment]
No thanks -- when I'm debugging or need devel info, I can switch over to the non-minified version.

**Comment by twistylittleworkshop** [comment]
Not at the moment, thank you. Thanks for your time on this.
