### ISSUE TITLE
Support more Infocom 

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/ifvms.js#54]
Support more Infocom games.

 - [x] Sherlock has a bug where it tries to set/check attribute 48

**Comment by fredrikr** [comment]
- The in-game hints menu in Sherlock (z5) and Nord and Bert (z4) are broken. No key presses are detected, so you can't select items or even exit the menu.
- The form at the beginning of Bureaucracy doesn't work. You get a more prompt and the game locks up.

**Comment by curiousdannii** [comment]
I can't get Bureaucracy to work in Gargoyle or Windows Frotz either.

**Comment by curiousdannii** [comment]
The problem with Bureaucracy was the same as #56, so that's fixed now. Because the cursor doesn't show it's not easy to see where you're meant to be typing, but it does work. Maybe that's by design, but I think you're meant to be able to have input in both windows, so I'll look into that.

**Comment by curiousdannii** [comment]
I couldn't reproduce any fatal errors in Sherlock anymore, so I think we're good for now. If anyone find any additional problems with Infocom games please make a new issue. :)
