### ISSUE TITLE
zvm.js fails on Windows w/node v9.2.0

### ISSUE THREAD

**Issue by DLehenbauer** [curiousdannii/ifvms.js#58]
The problem is that the below code from MemoryView() assumes that a TypedArray's view always spans the entire ArrayBuffer.
```javascript
// Typed arrays
if ( buffer.buffer )
{
    buffer = buffer.buffer;
}
```
However, this is not necessarily true.  Consider:
```javascript
var a = new ArrayBuffer(10);
var i = new Int8Array(a, 3, 3);
console.log(i.byteLength);                // <- Constructed view is from 3..6
console.log(i.buffer.byteLength);         // <- ...but underlying buffer is still 0..9
```
In particular, for very short files, node returns the result of fs.readFileSync(..) in an 8kb buffer w/the contents at a non-zero offset.  This causes file.identify() to fail immediately since the expected FourCC/zcode version is not at offset 0.

(Simple fix.  I'll send a PR shortly.)

**Comment by curiousdannii** [comment]
I can't reproduce this in Node 9.3. Do you have a test file?

**Comment by DLehenbauer** [comment]
I think the trick is that the *.z3 file needs to be shorter than Node.js's minimum/default I/O buffer size.

Give this a try:
```javascript
const fs = require('fs');

const z3 = new Uint8Array([
    0x03, 0x00, 0x00, 0x00, 0x00, 0x83, 0x00, 0x83, 0x00, 0x7E, 0x00, 0x40, 0x00, 0x00, 0x00, 0x7E,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x5A,
    0x04, 0x00, 0x00, 0xB2, 0x54, 0xD8, 0xE0, 0xA5, 0xBB, 0xBA]);

fs.writeFileSync('./repro.z3', z3);
```
If for some reason the above doesn't work, you can construct the test case with something like:
```javascript
const extraByte = new Uint8Array([0xFF, ...followed by bytes from above...]);
const z3 = new Uint8Array(extraByte.buffer, 1);  // Elide the extra byte
vm.prepare(z3, ...);
```
(BTW - I also repro'd w/Ubuntu and node v8.9.1.  I think the trick is that that the z-code file needs to be short enough that ```fs.readFileSync()``` copies into a default/minimum sized I/O buffer.)
