### ISSUE TITLE
Need help upgrading from 0.1.0

### ISSUE THREAD

**Issue by statico** [curiousdannii/ifvms.js#75]
This is an awesome project, and I'd like to stay current, but I'm having a lot of trouble.

I built a small HTTP server on top of ifvms.js here: https://github.com/statico/ifhttp/blob/master/server.js

It powers a text adventure game on my web site here: https://langworth.com

Unfortunately, with the latest code, I'm having a lot of trouble figuring out how to continue emulating this on the server side. Is there a way I can send commands and get output to the current version of the ZVM, similar to how my server works and how the "bootstrap" method worked in v0.1.0?

Or do I need to write a Glk subclass? If so, can you give me some pointers? The Glk and GlkTerm and DumbGlk seem closely tied to readline, and I have no idea what "Dialog" is. Can you give me a few pointers?

I appreciate the help.

**Comment by curiousdannii** [comment]
The CLI script shows how to join all the pieces together: https://github.com/curiousdannii/ifvms.js/blob/master/bin/zvm.js

Yes you could write a Glk subclass, but it might be simpler just to run it as a separate process and pipe commands in and pipe output out. (Of course you could do that with regular C interpreters too.) If you wanted to keep it all in JS, you might like to look at the [GlkOte docs](https://eblong.com/zarf/glk/glkote/docs.html) which show how the GlkOte protocol works. You'd want to replace DumbGlkOte with your own subclass of GlkOte providing new `update_content` functions etc.

**Comment by statico** [comment]
Thanks for responding. I appreciate it!

The reason I don't want this hosted entirely in the browser is because there are easter eggs and I don't want anyone to have access to the compiled .z8 file, so server-side is a must.

I saw `bin/zvm.js`, but it delegates most of its functionality to a bunch of different GlkOte classes, which I simply don't have the time to understand right now. The older bootstrap.js example was much easier because I could send the VM commands and read back a stream of text, even with CSS.

I'm going to stick with 0.1.0 for now.
