### ISSUE TITLE
Add Quixe style autosaves

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/ifvms.js#8]
Add Quixe style autosaves

**Comment by curiousdannii** [comment]
@erkyrath Any thing I should know about autosaves?

Present a `do_autosave` function, handle auto restoring, call `Glk.restore_allstate`? That's most of it isn't it?

Will GlkOte start out empty when autorestoring?

**Comment by erkyrath** [comment]
Yes, it starts out empty. 

Yeah, that's the sequence. I think. It's messy enough that I have to re-figure out the code I wrote every time I look at it. I apologize a lot.

**Comment by curiousdannii** [comment]
@erkyrath I think I have made it correctly save an autosave now. Restoring will be the tricky part ;)

Should I be keeping the transcript streams in the autosave? Will it be able to resume them?

**Comment by erkyrath** [comment]
glkapi.js saves all open streams (including the mode and mark position). When restoring, it tries to reopen file streams. If the file is missing, it tries to recreate it (even if the file was just being read). If it can't create the file, it creates a temporary file (in the usual temporary directory) and opens *that* -- the user probably won't be able to find it, but at least the game won't crash on an invalid stream reference.

This is all a bundle of hacks, of course.

**Comment by curiousdannii** [comment]
@erkyrath I think this is working now. I've written a new dispatch file which you should be able to just drop into Lectrote.
