### ISSUE TITLE
zvm ">command prompt"

### ISSUE THREAD

**Issue by johnd0e** [curiousdannii/ifvms.js#80]
`zvm` version 1.1.6, installed with npm on Windows.

`>` starting symbol breaks after using backspace. That causes visual artefacts after command launch.

E.g. type `>lookk` and press Backspace makes leading `>` to dissappear: `look`.
Then press Enter and get `llook` echo.

The same effect when starting previous command(s) from history buffer, available on Up/Down.

**Comment by curiousdannii** [comment]
This might just be a limitation of the basic console mode. It wasn't intended to be a perfect implementation.

**Comment by johnd0e** [comment]
@curiousdannii 
Why close this?

**Comment by curiousdannii** [comment]
Because I don't intend to fix it, sorry. The console app is very minimal and always will be. There are other interpreters that are more full featured.
